version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    container_name: guifler-bank-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: guifler_bank
      POSTGRES_USER: guifler
      POSTGRES_PASSWORD: guifler_pwd
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U guifler -d guifler_bank']
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data:
